spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# ====================== ↓↓↓↓↓↓ MinIO文件服务器 ↓↓↓↓↓↓ ======================
minio:
  url: http://116.211.105.103:9002
  accessKey: root
  secretKey: password
  bucketName: test

