spring:
  redis:
    timeout: 6000
    database: 0
    host: localhost
    port: 6379 #单实例redis用这个配置
    password:
    lettuce:
      pool:
        max-active: 1000 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 3 #连接池中的最小空闲连接
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）