spring:
  mail:
    # 配置默认编码
    default-encoding: UTF-8
    # 配置邮件服务器地址
    # qq邮箱为smtp.qq.com          端口号465或587
    # sina    smtp.sina.cn
    # aliyun  smtp.aliyun.com
    # 163     smtp.163.com       端口号465或994
    host: smtp.163.com
    # 配置用户的账号
    username: huanglei421023@163.com
    # 配置密码,注意不是真正的密码，而是刚刚申请到的授权码
    # 使用 jasypt 加密密码，使用com.xkcoding.email.PasswordTest.testGeneratePassword 生成加密密码，替换 ENC(加密密码)
    password: ENC(Q+Lrcb3gzd9xi/NyEwWw+xQk/hj26w0jxNu1UISJjQ8=)
    # 配置邮件服务器的端口(465或587)
    port: 465
    properties:
      mail:
        debug: true
        smtp:
          auth: 'true '
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          ssl:
            enable: true
          starttls:
            enable: true
          statics:
            required: true
    protocol: smtp
# 为 jasypt 配置秘钥
jasypt:
  encryptor:
    password: yolo